name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  win:
    name: windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
    
      - name: Restore
        run: dotnet restore IT.Id.sln
    
      - name: Build
        run: dotnet build IT.Id.sln --configuration Release --no-restore 
    
      - name: Test
        run: dotnet test IT.Id.Tests/IT.Id.Tests.csproj

  linux:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
    
      - name: Restore
        run: dotnet restore IT.Id.sln
    
      - name: Build
        run: dotnet build IT.Id.sln --configuration Release --no-restore 
    
      - name: Test
        run: dotnet test IT.Id.Tests/IT.Id.Tests.csproj

  mac:
    name: mac
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
    
      - name: Restore
        run: dotnet restore IT.Id.sln
    
      - name: Build
        run: dotnet build IT.Id.sln --configuration Release --no-restore 
    
      - name: Test
        run: dotnet test IT.Id.Tests/IT.Id.Tests.csproj

  publish:
    needs: [linux, win, mac]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: IT.Id/IT.Id.csproj
            NUGET_KEY: ${{secrets.NUGET}}
